/* The legal documents in English: the master text.

   Each translation (./tr.js, ./de.js, …) renders this text in its own
   language, with the same documents and sections in the same order, and
   carries this file's `version`. ./index.js shows a translation only while
   its version matches, so a change here shows English (with a note in the
   person's language) until every translation follows. Every translation
   says that the English text prevails where the law allows. The Turkish
   KVKK notices (tr.js › kvkk, consent) exist only in Turkish and are
   authoritative in Turkish.

   These are drafts for review by lawyers in Canada (where the controller,
   VOTEBT, is registered: Ontario), and in Türkiye and the EU before launch
   there: docs/LEGAL.md lists the open legal decisions. Every fact here must
   match the code and docs/ (PRIVACY_PERMISSIONS, MEDIA, ANALYTICS, PUSH,
   GENDER, the export bt_export and the bt_retention_* jobs). Change both
   together, then bump `version` here and in every translation.

   Placeholders: {controllerName}, {controllerAddress}, {contact} and
   {hostingRegion} are filled from the build's settings (docs/LEGAL.md).
   Without a value, `pending` stands in: nothing is ever invented.

   Text: a section is [heading, body]; a line break in a body starts a new
   line (lists start with “• ”). No dashes as punctuation and no
   semicolons, as everywhere in Vote's words. */
export default {
  lang: 'en',
  version: '2026-10-13',
  pending: 'not yet published',
  docs: {
    privacy: {
      title: 'Privacy Policy',
      sections: {
        intro: ['About this policy', 'This policy explains what personal data Vote collects when you use the Vote: Better Together app (“Vote”) and its web pages, why, on what legal basis, who receives it, how long it is kept and what your rights are. Vote is a dating app in which the community reads pairs of people, and nobody is introduced to anyone without saying yes. It is only for adults aged 18 or over.'],
        controller: ['Who is responsible', 'The data controller responsible for your personal data is:\nName: {controllerName}\nLegal form: a sole proprietorship registered in Ontario, Canada, run by its owner\nAddress: {controllerAddress}\nContact: {contact}\nIn the app you can reach us at any time under Settings › Help & support.\nThe owner of VOTEBT is the person accountable for Vote’s privacy practices under Canada’s PIPEDA, and the person in charge of the protection of personal information under Quebec law. You can reach them at the contact above.'],
        collect: ['What we collect', '• What you give us: your sign-in (Apple, Google or e-mail), first name, birth date, gender and pronouns, who you want to see, what you are looking for, relationship style and family plans, your photos, your city, and the answers, prompts, interests and tastes you add to your profile.\n• Optional answers that are sensitive: your beliefs (spirituality, religion, politics), your habits (drinking, smoking, cannabis), a diet that can reveal a religion (such as halal or kosher) and an identity beyond woman or man (for example trans or non-binary). See “Sensitive information and your explicit consent”.\n• What you do in Vote: likes, notes and passes, matches, messages and chat photos, your reads of pairs (your answer, how strongly you felt it, what you noticed, a first date you imagined and how long you looked before answering), the pairs you propose or follow, introductions and your answers to them, your answers after a date, blocks, reports and your requests to our support team.\n• Your settings: who can see each part of your profile, your community, notification and privacy settings, and the consents you gave or withdrew.\n• From your phone: two random IDs made by the app (an installation ID, sent with the platform, app version, language and time zone, and an install ID kept in the phone’s secure storage, of which Vote’s servers keep only a one-way hash), a push token if you turn on notifications, and an approximate position, rounded to about 1 km on your phone, only if you choose “Use my current location”.\n• Technical data: your IP address and the details of each request your phone sends to Vote’s servers, and crash reports if the app crashes.\n• From other members: what they do that involves you, such as liking you, reading a pair you are in, proposing you or reporting you. You only ever see these as counts or results, never who.\n• From Apple or Google, if you sign in with them: an identifier, the e-mail address they share (with Apple this may be a private relay address) and, if they share them, your name and, with Google, a profile picture. Our sign-in system keeps what they share. After an Apple sign-in on iPhone, Vote also keeps a token from Apple, sealed so only Vote’s servers can use it, to revoke Vote’s access when you delete your account. Vote uses only your first name, to start your profile.'],
        bases: ['Why we use it, and our legal bases', 'We use your data only for these purposes, each on the legal basis given (article 6 of the GDPR, article 5 of Türkiye’s KVKK):\n• To run your account and the service you asked for: sign-in, your profile and its audiences, Discover, likes, matches and chat, community reading, introductions, the notifications and optional features you turn on, and help and support. Basis: performance of our contract with you (GDPR art. 6(1)(b), KVKK art. 5(2)(c)).\n• Sensitive information: only with your explicit consent (GDPR art. 9(2)(a), KVKK art. 6), see the next section.\n• To keep Vote safe and fair: handling reports, moderation and appeals, refusing threatening words, preventing fake accounts, spam and manipulation of reads, limiting how much each account can do, security logs and crash reports. Basis: our legitimate interest in a safe community and a working service (GDPR art. 6(1)(f), KVKK art. 5(2)(f)), and our legal obligations where they apply (GDPR art. 6(1)(c), KVKK art. 5(2)(ç)).\n• Usage statistics: in the EU and EEA, the UK and Türkiye only with your consent (GDPR art. 6(1)(a), KVKK art. 5(1)). Elsewhere, our legitimate interest in improving Vote, and you can turn them off.\n• To establish, exercise or defend legal claims and to answer lawful requests from authorities. Basis: our legitimate interest and legal obligations (KVKK art. 5(2)(ç) and (e)).\nWhere we rely on legitimate interest, we have weighed it against your rights and you can object (see “Your rights”). Giving us your data is voluntary, but without the basics (your sign-in, first name, birth date, gender, who you want to see, what you are looking for, two photos and your city) Vote cannot show you to anyone or anyone to you.'],
        sensitive: ['Sensitive information and your explicit consent', 'Some information is special under data protection law because it can reveal your religion or beliefs, political opinions, health, sex life or sexual orientation. In Vote that is your beliefs and politics, your habits including cannabis, a diet that can reveal a religion, an identity beyond woman or man, and who you want to see, which together with your gender can reveal your sexual orientation. A pair you appear in can also show readers who you are interested in, for example a pair of two women.\nVote processes this information only with your explicit consent. The app asks for it separately, before you add the information, and says exactly what each consent covers. Belief and habit questions are optional and you can skip them. You can withdraw a consent at any time in Settings. Withdrawing deletes those answers from your profile and stops their use from then on, and it does not affect what happened before. Who you want to see is needed for matching, so without that consent Vote cannot show you to anyone or anyone to you.\nThese answers are shown only to the audience you choose for each part of your profile. At first, beliefs are shown to your Connections and habits to Potential dates, so readers do not see them. They appear in the Bond, which compares only what the person looking can see of both people. They are never used to order Discover, to choose pairs or to rank anyone, and never in usage statistics.\nIn countries that criminalise same-sex relationships, Vote offers fewer identity choices, does not show readers pairs of two people of the same gender or pairs with a non-binary person, and lets only nearby members read pairs unless you choose otherwise.'],
        visibility: ['Who sees your profile', 'You choose an audience for each part of your profile: Everyone, Potential dates, Connections or Only me.\n• Community readers see the photos you allow in Vote and the parts set to Everyone.\n• People who see you in Discover, among the people who liked them or in an introduction also see the parts set to Potential dates.\n• Your connections (a match or an accepted introduction) also see the parts set to Connections.\n• Only me is never shown to anyone.\nYour first name is always shown, and Vote never asks for your last name. Your birth date is never shown: people see your age, unless you hide it, and your zodiac sign only if you choose to show it. Readers never see your distance or when you were active. “Incognito” shows you only to people you like and takes you out of community Vote. Pausing your profile hides you from Discover, pairs and introductions until you come back.'],
        community: ['Community reading', 'If you appear in community Vote (Settings › Community › “Appear in community Vote”), other members may be shown you and another person as a pair and asked whether the two of you make sense together. This is how it works:\n• Readers see your first name, the photos you allow in Vote and the parts of your profile set to Everyone, which at first include your age, gender, city, what you are looking for, height, personality answers, tastes, prompts and interests. They never see your distance, your activity or who else read.\n• A read belongs to the pair, never to one person. Vote gives no one a score, rating or rank, and keeps no number about how readers see you.\n• A pair’s result is shown only once at least five people have read it, as a share rounded to 5% together with a word such as “Most”, “About half” or “Few”.\n• You never learn who read, proposed or followed you, and readers never learn whether the two of you met or talked.\n• Nobody is introduced or connected without both people saying yes.\n• You choose who may read your pairs (anyone, people nearby or only verified members), which photos appear in Vote, and whether you allow introductions, proposals and follows. You can leave community Vote at any time.\nBecause a pair can show readers who you are interested in, the app asks for your explicit consent before you appear in pairs.'],
        location: ['Location', 'Vote shows your city or neighborhood, never your coordinates. Its servers store your location only as the nearest point of a grid about 5 km wide, used to work out rounded distances and who is within each other’s distance. Once your profile is set up you can change your city but not remove it, and your city and Discover filters can be changed only a limited number of times a day, so nobody can use the distance Discover shows to work out where someone lives. When you search for your city, the text you type is sent to the Open-Meteo place search service. If you choose “Use my current location”, Vote asks your phone for its approximate location once and sends the rounded coordinates to the BigDataCloud reverse geocoding service to find your city, and nothing else about you. You can always type your city instead. Vote never follows your location in the background.'],
        permissions: ['Permissions', 'Vote asks your phone for a permission only when you use something that needs it: approximate location only when you tap “Use my current location”, the camera only if you choose to take a photo, and notifications only if you turn them on. To add a photo you choose it in your phone’s own photo picker, which shares only the photos you pick, so Vote never asks for your photo library. Vote never asks for your contacts, your precise location, your microphone or permission to track you.'],
        photos: ['Photos', 'Your phone encodes every photo again before sending it, which removes its location data, and Vote’s servers check it and encode it once more. Photos are stored privately. Someone gets a link to one of your photos only while your settings and your relation to them allow it, and each link, made only by Vote’s servers, works for at most about three minutes (one minute for a photo in chat). After a block, or when you hide a photo or turn on “Incognito”, no new link is issued. A link already issued keeps working until it runs out, and a photo already on someone’s screen may stay there until they leave it. Every new profile photo is checked by a person on Vote’s team before anyone else sees it, and your first photo must clearly show your face. Vote uses no automated face recognition or image classification.'],
        messages: ['Messages and chat photos', 'Messages are stored so the two of you can read them, and only the two people in a conversation can open it. Vote’s moderation tools show reports, not conversations. When you both have read receipts on, members whose plan includes read receipts see when you read their messages. Turning read receipts off hides yours and theirs. A message that has not reached Vote yet is kept on your phone so it can be sent again without being sent twice. After 24 hours it is no longer used and it is deleted the next time you open Vote. Signing out removes it at once.\nA photo sent in chat stays in the conversation, where the two of you can open it until the conversation ends (an unmatch, a block or a deleted account). Then Vote deletes it. A photo sent as “View once” can be opened by the other person one time. While it is open, Vote asks the phone to block screenshots and screen recording, but nobody can prevent a photo of the screen, so send only what you are comfortable with. Once it has been opened nobody can open it again, and Vote deletes it within 24 hours (it is kept that long only so it can be reported). If someone reports a chat photo, it is kept for Vote’s safety team until the report is closed, and every time the team opens it is recorded.'],
        astrology: ['Today’s sky and The sky between you', 'Both are optional, for fun only, and off until you turn them on. Astrology never affects who you see, who you are paired with or any ranking.\n• Today’s sky is a short daily reading on your own profile, calculated on Vote’s own servers from your birth date and, only if you add them, your birth time and birth place (the city, its approximate coordinates and its time zone). Only you see it. Each day’s reading is kept for 30 days.\n• “The sky between you”, in a chat, compares your birth chart with the other person’s. It opens only once you have both turned it on for that conversation, and the other person is not told when you turn it on. Either of you can turn it off at any time, which closes it for you both. Neither of you ever sees the other’s birth date, time or place, although a reading can hint at a little of them, for example that the other person gave a birth time. The reading is kept unchanged while it is open, deleted when either of you turns it off, and all of it is deleted within a day after the conversation ends.\nYour birth time and place are used only for these two features, are never shown to anyone and are never used for matching. You can remove them at any time. The words you read are written in advance by Vote and chosen by the calculation: no AI writes them and nothing about you is sent to an AI provider.'],
        afterDate: ['After a date, and first dates readers imagine', 'A few days into a conversation in which you have both written, Vote may ask you, and only you, whether you met, whether you are still talking and whether you would like to see them again. Answering is up to you. Your answers are kept with the conversation and never shown to the other person, who does not learn whether you answered. Vote uses them, counted together with everyone else’s, to learn which introductions really work. If you turn on “Share how my dates go” (Settings › Community), people who follow a pair you are in can see “they met”, “still talking” or “want to meet again”, but only when both of you have it on and both said yes. A no, or one person’s answer, is never shown. With it on, you can see the same for the pairs you follow.\nWhen you read two people together you may imagine their first date from three choices (when, what and where), kept with your read. Once at least five readers imagined one, the two people see the date most of them chose, part by part, with their introduction and at the top of their conversation. Never a date only one reader chose, never how many or who.'],
        records: ['Other records', 'Vote also keeps when you last opened “What your votes led to” on the Vote tab (the day and the time, not what it showed), whether you read pairs nearby or worldwide, the phrases you saved with the earlier “Saved phrases” feature, how many likes, notes and reads you have used in the current period, and, so that the people with the fewest possible pairs are paired first, about how many people your preferences and theirs allow you to be paired with (a number, never who) and when Vote last found no one new to pair you with.'],
        notifications: ['Notifications on your phone', 'If you turn on notifications, your phone’s push token is stored for this installation and sent, with each alert, to Apple’s push notification service, or on Android to Google’s Firebase Cloud Messaging. Vote sends its alerts directly to these services and uses no other push service. An alert says only what happened, such as “You have a new message”. It shows a first name only if you turn on “Show names in alerts”, and the start of a message only if you turn on “Show message text in alerts” (Settings › Notifications). Signing out or turning notifications off removes the token.'],
        emails: ['E-mails from Vote', 'Vote sends e-mails only when you need them: to confirm your address, to sign in or reset your password, and to answer a request you made, for example to support or to delete your account. Vote sends no newsletters or promotional e-mails. If it ever wants to, it will ask for your express consent first, and each such e-mail will say who sent it, how to reach us and how to unsubscribe in one step, as Canada’s Anti-Spam Legislation (CASL) and similar laws require. An unsubscribe takes effect within 10 business days at the latest.'],
        analytics: ['Usage statistics', 'Vote counts how the app is used (for example that a vote or a match happened, or that a screen was loaded) in its own database, never at an analytics company and never for advertising. It records no message text, photos, profile answers, gender or orientation, beliefs, locations or what you answered on a pair. The counts are linked to your account and are part of your data export. In the EU and EEA, the UK and Türkiye they stay off until you turn on “Help improve Vote” (Settings › Privacy). Elsewhere they are on until you turn that off. While it is off, nothing is recorded. The counts are deleted after 13 months and lose their link to you when you delete your account.'],
        technical: ['Crash reports and technical data', 'When crash reporting is set up and the app crashes or hits an error, a report with technical details (what failed, the app version, the device model and system version, and your account’s random ID) is sent to Vote’s crash reporting service, Sentry. Names, e-mail addresses, messages, links and locations are removed on your phone before it is sent. No screenshots or recordings of your screen are taken, and Sentry is set not to store IP addresses.\nWhen you sign in, Vote records a random installation ID created by the app, with the platform, app version, language and time zone, to keep your sign-in and notifications tied to the right device. The app also keeps a random install ID in your phone’s secure storage, so on iPhone it stays after the app is deleted and reinstalled. Vote’s servers keep only a one-way hash (SHA-256) of it with your account, and use it against ban evasion and clusters of fake accounts. Neither ID is derived from your phone’s hardware or advertising identifiers, and neither affects what anyone sees in Vote.\nOur hosting provider processes your IP address and the details of each request to deliver the service and protect it, and keeps security logs of sign-ins. Vote uses no advertising identifiers, does not track you across other apps or websites, and stores on your phone only what the app needs: your sign-in in the phone’s secure storage, the installation ID, your settings and temporary copies of what you have seen. Vote’s web pages set no cookies and load nothing from other sites.'],
        safety: ['Safety, moderation and support', 'A report keeps the reason you chose, any note you add and, for a photo sent in chat, that photo until the report is closed. By default, reporting someone also blocks them. Vote’s safety team sees the report, the reported account and its history of reports. Every decision, and every time the team opens a reported photo, is recorded with who did it and why. Nobody is told who reported them. Decisions are made by people on Vote’s team, never by software alone.\nWhen Vote’s team bans an account, one-way hashes (SHA-256) of its normalised e-mail address, its Apple or Google sign-in identities and its install IDs go on a ban list, with the reason. Nobody can read an address or an ID from the list. It is kept after the banned account is deleted, until the ban is lifted. A new account that matches it is suspended until a person on Vote’s team has looked at it.\nBefore a message, a caption or a like’s note goes, the app on your phone checks it against short lists of words. For insults it asks “Are you sure?”, and you decide. Under a message you receive with such words it asks whether it bothers you, with a way to report it. These checks happen only on your phone, and nothing about them is sent or recorded. Vote’s servers refuse a message, note or profile text with a threat of sexual violence, words telling someone to kill themselves or a slur on a short list, and a refused text is not stored.\nWhen you write to Vote from Settings › Help & support, or appeal a suspension, your message and our answer are kept with your account so you can see them in the app. Only Vote’s staff can read them, and they are deleted with your account.'],
        purchases: ['Paid plans', 'Vote is free to use, with the Vote Free plan. Paid plans, Vote Plus and Vote Max, are not on sale yet. If Vote offers them where you live and you buy one, Apple handles the payment and Vote never sees your card or Apple ID details. Vote keeps what the App Store reports about the subscription (the product, its transaction IDs, its status and dates, and whether it renews) and a random token that ties the purchase to your Vote account, so your plan follows you and can be restored.'],
        profiling: ['Automated processing and profiling', 'Some parts of Vote are worked out by software. None of them makes a final decision about you with legal or similarly significant effects.\n• Discover: people are ordered by how much your two profiles make sense together on paper (what you are each looking for, relationship style, family plans, distance, age, shared interests and tastes, and your “this or that” answers), by a daily random draw and by whether they already liked you. Nobody is ranked by attractiveness, and being liked by many people raises no one.\n• Pairs: software chooses which plausible pairs readers see. Everyone gets the same kinds of places, nobody is in more than a small number of pairs at once, and parts of a profile set to Only me are never used.\n• Reads: to resist fake accounts and coordinated voting, how much a read counts can depend on how new the account is, whether it is verified, whether the reader has interacted with one of the two people, how quickly and how uniformly the reader tends to answer, and bursts of new accounts reading the same pair. These weights are never shown, never kept as a score about anyone, and only change how much a read counts in a pair’s result. With each introduction, Vote keeps the pair’s result and how the pair was found, to learn over time which results really lead to conversations. Message content is never used for this.\n• Kind words: Vote’s servers refuse a short list of threatening words and slurs (see “Safety, moderation and support”).\n• Ban list: a new account that matches a banned account’s hashed e-mail address, sign-in or install ID is suspended automatically, until a person on Vote’s team has looked at it.\nIntroductions come from what people, the readers, say, and happen only if both people say yes. Moderation decisions are made by people. You can object to this processing, or ask a person on our team to look at something that affects you, through Settings › Help & support.'],
        recipients: ['Who receives your data', 'Other members see what your settings allow (see “Who sees your profile”). Beyond them, we share personal data only with:\n• Supabase, our hosting provider, for the database, sign-in, private file storage and server functions. Where its servers are: {hostingRegion}\n• Apple, for Sign in with Apple and its push notification service and, if you buy a plan, for the App Store, which handles the payment.\n• Google, for Google sign-in and notifications on Android (Firebase Cloud Messaging).\n• hCaptcha or Cloudflare Turnstile, only if Vote turns on a check against automated sign-ups: the service receives the IP address and device signals of whoever completes the check.\n• Sentry, for crash reports, when crash reporting is on in the app you use.\n• Open-Meteo and BigDataCloud, which your phone contacts directly to search for your city and, only if you use your current location, to name it. They receive the text you type or rounded coordinates, and nothing else about you.\n• Authorities and courts when the law requires it, our advisers where needed to establish, exercise or defend legal claims, and a buyer or successor if Vote’s business is ever transferred, under this policy.\nSupabase and Sentry process data on our behalf, under data processing agreements, and may not use it for their own purposes. Apple and Google also process what they receive under their own privacy policies. Vote does not sell or rent personal data, shares none with advertisers or data brokers, uses no advertising or tracking tools, and sends nothing about you to any AI provider.'],
        transfers: ['International transfers', 'Where Vote’s data is stored: {hostingRegion}\nSome of our providers, including Supabase, Apple, Google and Sentry, are based in the United States or work with people and systems in other countries, so your data may be processed outside your country. When data leaves the EU or EEA or the UK for a country without an adequacy decision, we rely on the European Commission’s standard contractual clauses (with the UK addendum), or on an adequacy framework the provider is certified under, such as the EU-U.S. Data Privacy Framework. For people in Türkiye, transfers abroad follow article 9 of Law No. 6698 (KVKK): we use the standard contracts published by the KVKK Board and notify them to the Authority as required, or another safeguard that article allows. You can ask us for a copy of these safeguards through Settings › Help & support.\nVote is run from Canada and its database is in Canada, so for people in Canada the data Vote stores stays in Canada, apart from what the providers above process in their own countries. For people in the EU and EEA, data that comes to Vote in Canada is covered by the European Commission’s adequacy decision for Canada, which applies to organisations subject to PIPEDA. For people in the UK, it is covered by the UK’s adequacy regulations for Canada.'],
        retention: ['How long we keep data', 'We keep your data while your account exists and delete it when you delete your account (see “Deleting your account”), unless a shorter period below applies or we must keep something longer:\n• Chat photos: until the conversation ends. A “View once” photo: up to 24 hours after it is opened.\n• A message not yet sent, on your phone: 24 hours.\n• Today’s sky readings: 30 days. “The sky between you”: while it is open, and at most a day after the conversation ends.\n• Usage statistics: 13 months.\n• Records of notifications sent: 14 days. Operational records (job runs and app health counts): 30 days. Counters for limits: 2 days.\n• Records of uploads that were rejected or expired: 90 days.\n• What the App Store reports about subscriptions: 400 days.\n• An open report and a chat photo it concerns: until the report is closed, even after an account is deleted, without the link to the account. Records of moderation decisions are kept so moderation stays accountable, and are no longer linked to an account once it is deleted.\n• The ban list: until the ban is lifted, even after the banned account is deleted. Hashes of your install IDs: while your account exists.\n• Apple’s sign-in token: until it is revoked when you delete your account. If Apple can’t be reached, Vote tries again every hour.\n• Security logs kept by our hosting provider: only as long as needed for security.\n• Backups: our hosting provider keeps copies of the database for a short period, after which deleted data is gone from them too.'],
        security: ['Security', 'We protect your data with measures that fit the risk: connections only over encrypted HTTPS, rules on every table so each request sees only what its account may see, photos in private storage reachable only through short-lived links, location data removed from photos, staff access by role with two-step verification for sensitive actions and an audit log, and your sign-in kept in your phone’s secure storage. No system is perfectly secure. If a breach puts your rights at risk, we will tell you and the competent authority as the law requires.'],
        rights: ['Your rights', 'Depending on where you live, you have the right to:\n• Access your data and get a copy. Settings › Your data › “Export my data” makes a file (JSON) that you save or share from your phone’s share sheet. It holds what Vote keeps about you, including the messages others sent you, the actions Vote’s team took on your account with the reason given (never who acted or who reported you), when your devices were seen and, if Vote corrected which search you appear in to match your gender, a note of that. For a conversation that ended, it gives the reason only to the person who ended it. You can ask us for anything it does not include.\n• Correct it. Edit your profile, or ask us, for example to fix your birth date.\n• Delete it, with Settings › Delete account, or by asking us.\n• Take it with you: the export is a machine readable file (JSON).\n• Object to processing based on our legitimate interest, including profiling, and ask us to restrict processing in some cases.\n• Withdraw a consent at any time, without affecting what happened before.\n• Not be subject to a decision based solely on automated processing that significantly affects you (Vote makes none), and, in Türkiye, object to a result against you that comes solely from automated analysis.\n• Claim compensation for damage caused by unlawful processing, where the law provides for it.\n• Complain to a data protection authority: in Türkiye the Personal Data Protection Board (KVKK Kurulu, kvkk.gov.tr), after applying to us first, in the EU or EEA the authority where you live or work (listed at edpb.europa.eu), and in the UK the Information Commissioner’s Office (ico.org.uk).\n• Complain in Canada to the Office of the Privacy Commissioner of Canada (priv.gc.ca), and in Quebec to the Commission d’accès à l’information (cai.gouv.qc.ca).\nTo use a right, write to us in the app (Settings › Help & support, “Privacy and my data”) or to the contact under “Who is responsible”. We may ask you to confirm that it is you. We answer free of charge, within one month in the EU, EEA and UK (we may extend this by two months for complex requests and will tell you) and within 30 days under the KVKK.'],
        turkiye: ['If you are in Türkiye', 'Law No. 6698 on the Protection of Personal Data (KVKK) applies to your data. Our KVKK Information Notice (Aydınlatma Metni) and our Explicit Consent Notice (Açık Rıza Metni) are published in Turkish, their binding language, and are linked below this policy in the app and on our website. You can use your rights under article 11 of the KVKK by applying to us as described there, and we answer within 30 days. If we reject your application, if our answer is not enough or if we do not answer in time, you can complain to the KVKK Board within 30 days of our answer, and in any case within 60 days of your application.'],
        canada: ['If you are in Canada', 'Vote is run from Ontario, Canada. The Personal Information Protection and Electronic Documents Act (PIPEDA) applies to how we handle your personal information, and in Quebec also the Act respecting the protection of personal information in the private sector, as amended by Law 25. In plain words, we follow PIPEDA’s ten fair information principles:\n• Accountability: the owner of VOTEBT is responsible for your information and answers for it.\n• Identifying purposes: we tell you why we collect information, in this policy and in the app, before or when we collect it.\n• Consent: we ask for your consent, and for your express consent for sensitive information. You can withdraw it at any time, subject to legal or contractual limits, and we tell you what withdrawing means.\n• Limiting collection: we collect only what Vote needs for the purposes in this policy.\n• Limiting use, disclosure and retention: we use and share information only for those purposes, unless you agree or the law requires it, and keep it only as long as “How long we keep data” says.\n• Accuracy: you can correct your profile at any time, or ask us to.\n• Safeguards: we protect information with security that fits how sensitive it is (see “Security”).\n• Openness: this policy explains our practices in plain words.\n• Individual access: you can ask what we hold about you, how it is used and who received it, get a copy and have it corrected. We answer within 30 days, free of charge, and tell you if we need more time, as the law allows.\n• Challenging compliance: you can question how we follow these principles by writing to our privacy contact.\nPrivacy contact: {contact}\nIf you are not satisfied with our answer, you can complain to the Office of the Privacy Commissioner of Canada (priv.gc.ca). In Quebec, the person in charge of the protection of personal information is the owner of VOTEBT, reachable at the privacy contact. You can also ask for your computerised information in a structured, commonly used format (Settings › Your data › “Export my data”), and complain to the Commission d’accès à l’information du Québec (cai.gouv.qc.ca).\nVote’s database is in Canada. Some providers, such as Apple, Google and Sentry, process information outside Canada and outside Quebec (see “Who receives your data”), where the courts and authorities of those countries may be able to access it under their laws. Before using a provider we check that your information will be adequately protected, and our processors are bound by contracts to protect it. If a breach creates a real risk of significant harm to you, we will tell you and the Privacy Commissioner, and we keep a record of every breach.'],
        us: ['Notice for the United States, including California', 'This section is the notice required by the California Consumer Privacy Act, as amended by the California Privacy Rights Act, and by similar laws in other states.\n• Categories we collect, from the sources and for the purposes described above: identifiers (account ID, installation ID, e-mail address), customer records (name, photos), characteristics of protected classifications (age, gender and, if you add them, religion or beliefs and information revealing sexual orientation), commercial information (subscription records, if you buy a plan), internet or other electronic network activity (how you use the app), approximate geolocation (never precise geolocation), visual information (photos), and inferences only in the limited form described under “Automated processing and profiling”.\n• Sensitive personal information: account log-in, religious or philosophical beliefs, sex life or sexual orientation, and the contents of your messages. We use it only to provide the service you asked for, as the law permits, and never to infer characteristics about you.\n• We disclose personal information for business purposes only to the service providers listed above. We do not sell or share personal information (sharing meaning for cross-context behavioral advertising), and have not done so in the past 12 months. Vote is not for anyone under 18.\n• How long we keep each category: see “How long we keep data”.\n• Your rights: to know and access the personal information we collect, to delete it, to correct it, and not to be discriminated against for using these rights. Because we do not sell or share personal information, or use sensitive information beyond what the law permits, there is nothing to opt out of or limit. You can use your rights yourself or through an authorized agent, as described under “Your rights”. We verify each request and answer within 45 days, which we may extend once by 45 days, with notice.\n• Other states, such as Colorado, Connecticut, Texas and Virginia, give you similar rights. We process sensitive data only with your consent. If we decline your request, you can appeal by replying to our answer, and if the appeal is denied, you can contact your state’s attorney general.'],
        otherRegions: ['Other countries', 'If you live in Brazil, the LGPD gives you the right to confirmation and access, correction, anonymisation, blocking or deletion of unnecessary data, portability, information about who we share data with, and to withdraw consent, and you can complain to the ANPD. Wherever you live, if local law gives you further rights or requires more information than this policy gives (for example in Japan, South Korea, India or China), we honour them. Ask us through Settings › Help & support.'],
        children: ['Adults only', 'Vote is only for people aged 18 or over. The app checks your age from your birth date when you join, and members can report someone who may be under 18. Such reports are handled first. When we learn that an account belongs to someone under 18, we close it and delete its data, except what we must keep for safety or by law.'],
        deletion: ['Deleting your account', 'You can delete your account at any time in Settings › Delete account. Deleting it removes, at once and for good, your account, profile, photos, likes, reads, follows, matches, the conversations you were part of and their photos (the other person loses them too), introductions, blocks, your support requests and the reports you made that are closed. If you signed in with Apple on an iPhone, Vote also asks Apple to revoke Vote’s access to your Apple ID, and keeps trying every hour if Apple can’t be reached. Apple sign-ins on Android, or from before this version of Vote, can’t be revoked by our servers: you can remove Vote in your Apple ID settings. Deletion completes either way. If your account was banned, the ban list stays until the ban is lifted. A report still open when you delete your account, one you made or one about you, is kept, no longer linked to any account, until Vote’s safety team closes it, together with a chat photo it concerns, so that a safety review can finish. Usage statistics lose their link to you. Copies may remain in our hosting provider’s backups until those expire. Deleting your account does not cancel an App Store subscription: cancel it with Apple. If you only want a break, you can pause your profile instead. Our page “Deleting your account and data” explains each step, what is kept and why, and how to ask by e-mail if you can’t open the app.'],
        changes: ['Changes to this policy', 'We update this policy when Vote changes or the law requires it. The version and its date are at the end. If a change matters to you, we will tell you in the app before it takes effect, and where a change needs your consent, we will ask for it.'],
        language: ['Language of this policy', 'This policy is written in English and translated into the other languages Vote offers. If a translation and the English text differ, the English text prevails, unless the law where you live requires otherwise. For people in Türkiye, the KVKK Information Notice and the Explicit Consent Notice are authoritative in Turkish.'],
        contact: ['Contact', 'In the app: Settings › Help & support, “Privacy and my data”.\nOutside the app: {contact}\nAddress: {controllerAddress}']
      }
    },
    terms: {
      title: 'Terms of Use',
      sections: {
        about: ['These terms', 'These terms are an agreement between you and the business that operates the Vote: Better Together app (“Vote”, “we”):\nName: {controllerName}\nLegal form: a sole proprietorship registered in Ontario, Canada, run by its owner\nAddress: {controllerAddress}\nThey apply when you use the Vote app and its web pages. By creating an account you accept them, together with the Community guidelines. Our Privacy Policy explains how we handle your personal data.'],
        eligibility: ['Who can use Vote', 'You must be 18 or older and legally able to agree to these terms. One account per person: use your own photos, your real first name and your real age, and don’t create an account for anyone else. You may not use Vote if we have closed your account before, unless we agree.'],
        account: ['Your account', 'You sign in with Apple, Google or an e-mail address. Keep your sign-in secure, and tell us through Settings › Help & support if you think someone else is using your account. You are responsible for what is done with your account.'],
        service: ['How Vote works', 'In Discover you can like someone, like them with a note or pass, and two likes make a match. In community Vote, members read pairs of other people and say whether the two make sense together. Reads are opinions, not facts. A pair’s result is shown only after at least five people have read it, as a share rounded to 5% with a word such as “Most” or “Few”, and it belongs to the pair, never to one person. Once you have seen a pair’s result, your read on that pair is final. When readers see something strong, Vote may introduce the two people, and they are connected only if both say yes. Astrology in Vote is for fun only and never decides anything. Vote does not promise matches, introductions, dates or relationships.'],
        content: ['Your content', 'You own what you post: your photos, words and answers. You give us a worldwide, non-exclusive, royalty-free licence to store, copy, adapt (for example to resize a photo) and show your content in Vote, only according to your settings and only to run Vote. The licence ends when you delete the content or your account, except for copies kept for an open safety report or in backups until they expire, as our Privacy Policy explains. You must have the right to post what you post, and you may not post anyone else’s photos or personal details without their permission.'],
        conduct: ['Rules of conduct', 'Follow the Community guidelines. In particular, don’t:\n• harass, threaten or bully anyone, or attack anyone for who they are\n• post sexual content without consent, or anything sexual involving a minor\n• deceive or scam anyone, or ask anyone for money\n• impersonate anyone or use photos that aren’t yours\n• post anything illegal or that infringes someone else’s rights\n• advertise, sell or recruit\n• share someone’s messages, photos or personal details outside Vote without their consent, or reveal anyone’s sexual orientation or gender identity\n• use bots or scripts, scrape, copy or reverse engineer Vote, or get around its limits or security\n• create or coordinate accounts to sway reads'],
        limits: ['Limits and fair use', 'To keep Vote fair, each account can like, add notes, read pairs, propose pairs and send chat photos only up to certain limits in a period. The limits are shown in the app and may change. Reading pairs is the community’s shared work and is never sold. Vote may limit or stop automated or abusive use, and may give less weight to, or set aside, reads that look automated or coordinated.'],
        plans: ['Paid plans', 'Vote is free to use, with the Vote Free plan. Optional paid plans, Vote Plus and Vote Max, are not on sale yet. When Vote offers them, what each plan includes and its price are shown in the app before you buy, and Vote’s servers decide what your plan includes. A plan never changes how the community reads pairs or what a result means, and privacy settings, blocking and reporting are the same on every plan.'],
        subscriptions: ['Subscriptions', 'Where they are offered, Vote Plus and Vote Max are sold through the App Store as auto-renewing subscriptions. Payment is charged to your Apple ID, and the price and period are shown before you buy. A subscription renews automatically unless you cancel it at least 24 hours before the current period ends, in your iPhone’s Settings › your name › Subscriptions. Cancelling keeps the plan until the end of the period you paid for. Refunds are handled by Apple under its terms. A subscription belongs to the Vote account it was bought with. Deleting your Vote account does not cancel an App Store subscription: cancel it with Apple. Your rights as a consumer under the law are not affected.'],
        safety: ['Your safety', 'Vote does not run criminal background checks or verify identities, and photo verification is not available yet. Be careful with people you meet: take your time, meet in public, tell a friend and never send money. Report anyone who breaks these terms or makes you feel unsafe. If you are in danger, contact local emergency services first: Vote cannot send help.'],
        moderation: ['Moderation, suspension and appeals', 'We may remove content, limit features, or pause, suspend or close an account that breaks these terms, the Community guidelines or the law, or that puts others at risk. People on Vote’s team make these decisions. The only automatic measures are these: Vote’s servers refuse a short list of threatening words and slurs, a report blocks the reported person for the reporter by default, a reported chat photo is kept for review, and a new account that matches a banned account is suspended until a person has looked at it. We tell you about a restriction and, unless the law or someone’s safety prevents it, why. You can appeal from the screen your account shows or from Settings › Help & support, and a person on our team reviews your appeal and answers in the app. Anyone can report content or an account from its menu in the app.'],
        ending: ['Ending your account', 'You can pause or delete your account at any time from Settings. Deleting it removes your account, profile, photos, likes, reads, follows, matches, the conversations you were part of, introductions, blocks, your support requests and the reports you made that are closed. A report still open when you delete your account, one you made or one about you, is kept, no longer linked to any account, until Vote’s safety team closes it, together with a chat photo it concerns, so that a safety review can finish. We may close your account if you seriously or repeatedly break these terms, or if we stop offering Vote, and we will tell you in advance where we reasonably can.'],
        ours: ['Vote’s app and name', 'Vote, its name, design and software belong to us or our licensors. We give you a personal, non-transferable licence, which we may revoke, to use the app for its purpose under these terms. If you downloaded Vote from the App Store, Apple’s standard licence terms for apps also apply, and Apple is not responsible for Vote or its content.'],
        changesToVote: ['Changes to Vote', 'Vote is a young service. We may add, change or remove features, and Vote may sometimes be unavailable, for example for maintenance. We will tell you in the app about changes that matter to you.'],
        liability: ['Liability', 'We provide Vote with reasonable care and skill, but we cannot guarantee that it will always be available or free of errors, or how other members behave. As far as the law allows, we are not liable for indirect or unforeseeable loss, or for the conduct of other members on or off Vote. Nothing in these terms limits our liability for death or personal injury caused by our negligence, for fraud, intent or gross negligence, or any other liability that the law does not allow us to limit, and nothing affects your mandatory rights as a consumer.'],
        changes: ['Changes to these terms', 'We may update these terms. If a change matters to you, we will tell you in the app before it takes effect. If you don’t agree, you can delete your account before then. The version and its date are at the end.'],
        law: ['Law and disputes', 'These terms are governed by the laws of the Province of Ontario and the federal laws of Canada that apply there. If you are a consumer, you keep the protection of the mandatory law of the province or country where you live, including its consumer protection law, wherever it gives you more protection, and nothing in these terms takes that away. You can bring a claim in the courts of Ontario or, where your local law allows, in the courts where you live. Please write to us first through Settings › Help & support, so we can try to solve the problem together. In Quebec, the Consumer Protection Act applies to you in full. In the EU, the EEA and the UK you keep the protections of the law where you live and can go to its courts. In Türkiye you can also apply to the consumer arbitration committees and consumer courts.'],
        general: ['General', 'If a part of these terms is found invalid, the rest still applies. If we don’t enforce a right at once, we have not given it up. We may transfer these terms to a company that takes over Vote, and will tell you if we do. You may not transfer your account.'],
        language: ['Language of these terms', 'These terms are written in English and translated into the other languages Vote offers. If a translation and the English text differ, the English text prevails, unless the law where you live requires otherwise.'],
        contact: ['Contact', 'In the app: Settings › Help & support.\nOutside the app: {contact}\nAddress: {controllerAddress}']
      }
    },
    guidelines: {
      title: 'Community guidelines',
      sections: {
        real: ['Be real', 'Use your own photos and your real age. One person, one account. No impersonation.'],
        generous: ['Read generously', 'Every pair is two real people. Reads are about fit, never about ranking anyone or judging looks alone.'],
        final: ['A no is final', 'Don’t pressure anyone to accept a like, a match or an introduction.'],
        private: ['Keep private things private', 'Don’t share anyone’s messages, photos or details outside Vote without their consent, and never reveal anyone’s sexual orientation or gender identity.'],
        zero: ['Zero tolerance', 'Harassment, hate, threats, scams and sexual content without consent lead to removal.'],
        kind: ['Kind words', 'Vote never sends or shows threats of sexual violence, words telling someone to kill themselves, or slurs, and asks “Are you sure?” before words that may hurt. If a message bothers you, report it: a person on Vote’s team reviews it.']
      }
    },
    support: {
      title: 'Support',
      sections: {
        help: ['Getting help', 'Open Vote, then Settings › Help & support. You can ask about your account, privacy and your data, safety, or anything else. A person on Vote’s team answers there, in the app.'],
        appeals: ['Appeals', 'If your account was suspended or restricted and you think it was a mistake, open Vote: the screen your account shows has “Appeal or ask for help”. Your appeal is reviewed by a person, not decided automatically.'],
        report: ['Reporting someone', 'On any profile, pair, introduction or chat, open the menu and choose Report. Reports are confidential: the person is never told who reported them.'],
        privacy: ['Your data and privacy', 'For a copy of your data, use Settings › Your data › “Export my data”. To delete your account, use Settings › Delete account. For any other privacy request, write to us in the app under Settings › Help & support (“Privacy and my data”). Our Privacy Policy explains your rights.'],
        danger: ['If you are in danger', 'Contact local emergency services first. Vote cannot send help.'],
        signin: ['Can’t sign in', 'Use the sign-in method you chose when you joined (Apple, Google or e-mail). With e-mail, “Forgot password” on the sign-in screen sends a reset link.'],
        contact: ['Contact', 'If you can’t open the app: {contact}']
      }
    },
    deletion: {
      title: 'Deleting your account and data',
      sections: {
        inApp: ['Delete your account in the app', 'Open Vote, then Settings › Delete account, and confirm. You need to be signed in, and the deletion happens at once. It can’t be undone, so if you want a copy of your data, save it first with Settings › Your data › “Export my data”. If you only want a break, you can pause your profile instead.'],
        deleted: ['What is deleted, and when', 'At once and for good: your account and sign-in, profile, photos, likes and notes, reads, follows and the pairs you proposed, matches, the conversations you were part of and their photos (the other person loses them too), introductions, blocks, your settings and consents, your support requests and the reports you made that are closed. If you signed in with Apple on an iPhone, Vote also asks Apple to revoke Vote’s access to your Apple ID, and keeps trying every hour if Apple can’t be reached. Copies in our hosting provider’s backups are gone when those backups expire, after a short period.'],
        kept: ['What is kept, and why', 'A few things stay, only as long as needed:\n• If your account was banned: one-way hashes (SHA-256) of its e-mail address, sign-in identities and install IDs stay on the ban list until the ban is lifted, so the same person can’t simply start again. Nobody can read an address or an ID from them.\n• A report still open, one you made or one about you, and a chat photo it concerns: kept without any link to an account until Vote’s safety team closes it.\n• Records of moderation decisions: kept so moderation stays accountable, without the link to your account.\n• Usage statistics: they lose their link to you and are deleted after 13 months.\n• What the App Store reported about a subscription: up to 400 days.\n• Legal holds: if the law requires us to keep something, for example under a court order or a lawful request from an authority, or we need it to establish, exercise or defend a legal claim, we keep only that, only as long as required, and then delete it.'],
        email: ['If you can’t open the app', 'Write to us from the e-mail address of your Vote account, or tell us how you sign in (Apple, Google or e-mail) and the first name on your profile, and ask us to delete your account. We may ask you to confirm that it is you, so that nobody can delete someone else’s account. We delete it within 30 days at the latest, usually much sooner, and confirm by e-mail.\nE-mail: {contact}'],
        subscriptions: ['Subscriptions and signing in again', 'Deleting your Vote account does not cancel an App Store subscription: cancel it in your iPhone’s Settings › your name › Subscriptions. Apple sign-ins on Android, or from before this version of Vote, can’t be revoked by our servers: you can remove Vote in your Apple ID settings. If you later sign in again with the same Apple, Google or e-mail account, a new, empty account starts, unless that account was banned.']
      }
    }
  }
};
